# docker-compose.yml

version: '3.8'

services:

  # Banco de Dados PostGres
  db-PostGreSQL:
    image: postgres
    container_name: db
    # automatically restarts the container - Docker daemon on restart or
    # the container itself is manually restarted
    restart: always
    environment:
      # Essa variável de ambiente é necessária para você usar a imagem PostgreSQL. 
      # Não deve estar  vazio ou indefinido. Esta variável de ambiente define a senha 
      # de superusuário para PostgreSQL
      POSTGRES_PASSWORD: "root"
      # Essa variável de ambiente opcional é usada em conjunto com POSTGRES_PASSWORDpara 
      # definir um usuário e sua senha. Essa variável criará o usuário especificado com 
      # poder de superusuário e um banco de dados com o mesmo nome. Se não for especificado, 
      # o usuário padrão postgresserá usado. 
      POSTGRES_USER: postgres
      # Variável de ambiente opcional, usada para definir um nome diferente para o banco
      # de dados padrão que é criado quando a imagem é iniciada pela primeira vez. 
      # Se não for especificado, o valor de POSTGRES_USER será usado.
      POSTGRES_DB: database
      # Variável de ambiente opcional, usada para definir outro local (subdiretório)
      # para os arquivos do banco de dados. O padrão é /var/lib/postgresql/data.
      # PGDATA: /var/lib/postgresql/data
      # Variável de ambiente opcional, usada para definir outro local para o log de transações
      # do Postgres. Por padrão, o log de transações é armazenado em um subdiretório da pasta
      # principal de dados do Postgres ( PGDATA). Às vezes, pode ser desejável armazenar o log
      # de transações em um diretório diferente, que pode ser apoiado por armazenamento com
      # diferentes características de desempenho ou confiabilidade.
      # POSTGRES_INITDB_WALDIR: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: /root/vols/postgres
        target: /var/lib/postgresql/data
    networks:
      net10:
        ipv4_address: 192.168.10.20        

  # Administração do Banco de Dados PostGres
  admim-db-PostGreSQL:
    image: dpage/pgadmin4
    container_name: db-adm
    # automatically restarts the container - Docker daemon on restart or
    # the container itself is manually restarted
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "marcos.antonio.carvalho@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "master"
    ports:
      - "54321:80"
    volumes:
      - type: bind
        source: /root/vols/pgadmin
        target: /var/lib/pgadmin
    depends_on:
      - db-PostGreSQL  # depende do rolê do Banco de Dados
    networks:
      net10:
        ipv4_address: 192.168.10.30

  # Aplicação Web em Python 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: "on-failure"
    environment:
      DATABASE_URL: postgresql://192.168.10.20:5432/database
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 80:80
    depends_on:
      - db-PostGreSQL        # depende do rolê do Banco de Dados
      - admim-db-PostGreSQL  # depende tambem do rolê da Administração do Banco de Dados
    networks:
      net10:
        ipv4_address: 192.168.10.10

# Rede do Microserviço (net10) que interliga a Aplicação (app) e 
# Banco de Dados (db) bem como a sua Administração (db-adm).
networks:
  net10:
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"
          gateway: 192.168.10.1


